config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection
  end

  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  get '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts

    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  root to: "base#site_index"



  # scope "/admin" do
  #   get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
  #   get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
  # end

  get 'pages/:id' => 'pages#show', :as => :pages


  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout

  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets

  match '/forgot_username' => 'users#forgot_username', :as => :forgot_username, :via => [:get, :post]

  post '/resend_activation/:id' => 'users#resend_activation', :as => :resend_activation

  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'

  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'manage_photos' => 'photos#create_photos', :as => :create_photos

  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags

  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events, :concerns => :paginatable do
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do
      member do
        get :unsubscribe
        put :approve
      end
    end
  end
  resources :comments do
    collection do
      delete :delete_selected
    end
  end
  resources :comments

  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities

  resources :users, :concerns => :paginatable do

    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'
      get 'activate'

      patch 'toggle_moderator'
      patch 'toggle_featured'

      patch 'change_profile_photo'
      patch 'update_account'
      patch 'deactivate'

      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'

      post 'assume'

      get 'statistics'
      match 'crop_profile_photo', :via => [:get, :put, :patch]
      match 'upload_profile_photo', :via => [:get, :put, :patch]
    end

    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        patch :accept
        patch :deny
      end
    end

    resources :photos, :concerns => :paginatable

    resources :posts, :concerns => :paginatable do
      collection do
        # get 'manage(/page/:page)', :action => :manage
        match :manage, :via => [:get, :post]
      end

      member do
        post :send_to_friend
        patch :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities, :concerns => :paginatable do
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      get :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected
      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update


end

app/views/shared/_add_friend_link.html.haml
= button_to :request_friendship.l, user_friendships_url(:user_id => current_user.id, :friend_id => user.id), :class => "btn btn-primary btn-xs", :id => "friend_request_#{user.id}", :remote => true
= ajax_spinner_for "friend_request_#{user.id}"

- content_for :end_javascript do
  :javascript
    $("#friend_request_#{user.id}").on('click', function() {
      $('#'+ $(this).attr('id') + '_spinner').removeClass('hide');
      $(this).attr("value", "Sending request ...");
    });

app/views/shared/_bio_help.html.haml
- if @user.vendor?
  = :user_vendor_offer.l
- else
  = :user_bio_help.l

app/views/shared/_explore.html.haml
-widget do
  %h4
    .small Explore
  %ul.list-unstyled
    - Category.all.each do |c|
      %li= link_to c.name, category_path(c)
    %li= link_to :whats_popular.l, popular_url, {:class => 'popular'}
    - Page.all.each do |page|
      - if (logged_in? || page.page_public)
        %li= link_to page.title, pages_path(page)

app/views/shared/_footer_content.html.haml
.col-sm-9
  %hr
  %h2=:whats_fresh.l
  %table{:width => '100%'}
    - @recent_activity.each do |activity|
      =render :partial => "activities/activity", :locals => {:activity => activity }
  =link_to fa_icon('plus-circle', :text => :see_all_activity.l), activities_path

.col-sm-3
  %hr
  %h2=:tags.l
  - tag_cloud @popular_tags, %w(css1 css2 css3 css4 css5) do |tag, css_class|
    = link_to tag.name, tag_path(tag.to_param), :class => css_class
  %p
    =link_to fa_icon('plus-circle', :text => :all_tags.l), tags_path

app/views/shared/_footer_links.html.haml
%ul.nav.nav-pills
  %li{:class => current_page?(home_url) ? 'active' : 'inactive'}
    %a{:href=>home_url, :title=>"#{configatron.community_name} " + :home.l}= :home.l
  - if !logged_in?
    %li{:class => current_page?(login_path) ? 'active' : 'inactive'}
      = link_to :log_in.l, login_path
  - else
    %li{:class => current_page?(logout_path) ? 'active' : 'inactive'}
      %a{:href=>logout_path, :title=>:log_out_of_your.l + " #{configatron.community_name} " + :account.l}
        =:log_out.l

  - Page.all.each do |page|
    - if (logged_in? || page.page_public)
      %li{:class => current_page?(pages_path(page)) ? 'active' : 'inactive'}
        = link_to page.title, pages_path(page)

  - if @rss_title && @rss_url
    %li#rss= link_to :rss.l, @rss_url, {:title => @rss_title}

app/views/shared/_friend_link.html.haml
%span.friend_request{:id => "friend_request_#{user.id}"}
  = link_to :request_friendship.l, user_friendship_path(current_user, user), :data => { :userid => user.id }, :class => "add_friend_button friendship_link", :remote => true, :method => :post
  %span.spinner{:style => "display:none"}
    = image_tag('spinner.gif')
    = "#{:request_friendship.l} ..."
-content_for :end_javascript do
  :javascript
    // This should be moved to someplae more generic
    $$(".friendship_link").each(function (link) {
      link.observe("ajax:loading", function () {
        var id = link.readAttribute('data-userid');
        $$('span#friend_request_' + id + ' span.spinner')[0].show();
        $$('span#friend_request_' + id + ' a.add_friend_button')[0].hide();
      });
      link.observe("ajax:complete", function () {
        var id = link.readAttribute('data-userid');
        new Effect.Highlight(link, 1);
      });
      link.observe("ajax:failure", function () {
        alert('#{escape_javascript(:sorry_there_was_an_error_requesting_friendship.l)}')
      });
      link.observe("ajax:success", function (data) {
        link.innerHTML = data;
      });
    });

app/views/shared/_header.html.haml
-# .navbar-toggle is used as the toggle for when the responsive design gets narrow and the navbar goes away
.navbar-header
  %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  = link_to configatron.community_name, home_path, :class => 'navbar-brand'
.navbar-collapse.collapse
  %ul.nav.navbar-nav
    = render 'categories/menu_item'
    = render 'clippings/menu_item'
    = render 'events/menu_item'
    = render 'forums/menu_item'
    = render 'posts/menu_item'
    = render 'users/menu_item'
    - if @header_tabs.any?
      - for tab in @header_tabs
        %li= link_to tab.name, tab.url
  %ul.nav.navbar-nav.pull-right
    = render 'messages/menu_item'
    = render 'sessions/menu_item'

app/views/shared/_jumbotron.html.haml
.box{html_options}
  %div{:class => "jumbotron #{html_options[:content_class]}"}
    =body

app/views/shared/_location_chooser.html.haml
#location_chooser
  %label= :country.l
  = select_tag(:country_id, options_from_collection_for_select(Country.find_countries_with_metros, "id", "name", selected_country), {:include_blank => true, :class => "form-control"})

  %br
  %label= :state.l
  = select_tag(:state_id, options_from_collection_for_select(states, "id", "name", (selected_state rescue nil)), {:disabled => states.empty?, :class => "form-control" })

  = ajax_spinner_for 'location_chooser'

  %br
  %label= :metro_area.l
  = select_tag(:metro_area_id, options_from_collection_for_select(metro_areas, "id", "name", (selected_metro_area rescue nil)), {:disabled => metro_areas.empty?, :class => "form-control" })

  = ajax_spinner_for 'location_chooser'

- js ||= nil
- if js
  :javascript
    function refreshLocationChooser(html) {
      $('#location_chooser').html(html);
      $('#location_chooser img').addClass('hide');
    }
    $(document).on('change', '#country_id', function(){
      $('#location_chooser img').removeClass('hide');
      $.post('#{users_metro_area_update_path}?country_id=' + $('#country_id').val(), {}, refreshLocationChooser);
    });
    $(document).on('change', '#state_id', function(){
      $('#location_chooser img').removeClass('hide');
      $.post('#{users_metro_area_update_path}?country_id=' + $('#country_id').val() + '&state_id=' + $('#state_id').val(), {}, refreshLocationChooser);
    });
- else
  -content_for :end_javascript do
    :javascript
      $(document).on('change', '#country_id', function(){
        updateElementFromPost($('#location_chooser'), '#{users_metro_area_update_path}?country_id=' + $('#country_id').val());
      });
      $(document).on('change', '#state_id', function(){
        updateElementFromPost($('#location_chooser'), '#{users_metro_area_update_path}?country_id=' + $('#country_id').val() + '&state_id=' + $('#state_id').val());
      });

app/views/shared/_login_sidebar.html.haml
-widget do
  %h4
    .small=:help.l
  %p
    =:dont_have_an_account.l
    %br
    = link_to :click_here_to_sign_up.l, signup_path
  %p
    =:forgot_your_password.l
    %br
    = link_to :click_here_to_retrieve_it.l, forgot_password_url
  %p
    =:forgot_your_username.l
    %br
    = link_to :click_here_to_retrieve_it.l, forgot_username_url

app/views/shared/_messages.html.haml
-[:notice, :error, :alert].each do |level|
  -unless flash[level].blank?
    %div{:class => 'alert alert-dismissible ' + flash_class(level), :role => 'alert'}
      %button.close{:type => 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
        &times;
      =content_tag :p, flash[level]

app/views/shared/_scripts_and_styles.html.haml
= stylesheet_link_tag 'community_engine'

- if forum_page?
  - unless @feed_icons.blank?
    - @feed_icons.each do |feed|
      = auto_discovery_link_tag :rss, feed[:url], :title => "Subscribe to '#{feed[:title]}'"

= yield :head_css

app/views/shared/_sidebar.html.haml
= render_widgets

app/views/shared/_widget.html.haml
.box{html_options}
  %div{:class => "well #{html_options[:content_class]}"}
    =body