config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection
  end

  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  get '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts

    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  root to: "base#site_index"



  # scope "/admin" do
  #   get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
  #   get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
  # end

  get 'pages/:id' => 'pages#show', :as => :pages


  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout

  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets

  match '/forgot_username' => 'users#forgot_username', :as => :forgot_username, :via => [:get, :post]

  post '/resend_activation/:id' => 'users#resend_activation', :as => :resend_activation

  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'

  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'manage_photos' => 'photos#create_photos', :as => :create_photos

  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags

  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events, :concerns => :paginatable do
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do
      member do
        get :unsubscribe
        put :approve
      end
    end
  end
  resources :comments do
    collection do
      delete :delete_selected
    end
  end
  resources :comments

  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities

  resources :users, :concerns => :paginatable do

    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'
      get 'activate'

      patch 'toggle_moderator'
      patch 'toggle_featured'

      patch 'change_profile_photo'
      patch 'update_account'
      patch 'deactivate'

      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'

      post 'assume'

      get 'statistics'
      match 'crop_profile_photo', :via => [:get, :put, :patch]
      match 'upload_profile_photo', :via => [:get, :put, :patch]
    end

    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        patch :accept
        patch :deny
      end
    end

    resources :photos, :concerns => :paginatable

    resources :posts, :concerns => :paginatable do
      collection do
        # get 'manage(/page/:page)', :action => :manage
        match :manage, :via => [:get, :post]
      end

      member do
        post :send_to_friend
        patch :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities, :concerns => :paginatable do
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      get :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected
      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update


end

app/models/sb_post.rb
class SbPost < ActiveRecord::Base
  acts_as_activity :user, :if => Proc.new{|record| record.user } #don't record an activity if there's no user
  include Rakismet::Model
  rakismet_attrs :author => :username, :comment_type => 'comment', :content => :body, :user_ip => :author_ip

  belongs_to :forum, :counter_cache => true
  belongs_to :user,  :counter_cache => true
  belongs_to :topic, :counter_cache => true

  format_attribute :body
  before_create { |r| r.forum_id = r.topic.forum_id }
  after_create  { |r|
    Topic.where('id = ?', r.topic_id)
    .update_all(['replied_at = ?, replied_by = ?, last_post_id = ?', r.created_at, r.user_id, r.id])

  }
  after_destroy { |r|
    t = Topic.find(r.topic_id)
    Topic.where('id = ?', t.id).update_all(['replied_at = ?, replied_by = ?, last_post_id = ?', t.sb_posts.recent.last.created_at, t.sb_posts.recent.last.user_id, t.sb_posts.recent.last.id]) if t.sb_posts.recent.last
  }

  validates_presence_of :user_id, :unless => Proc.new{|record| configatron.allow_anonymous_forum_posting }
  validates_presence_of :author_email, :unless => Proc.new{|record| record.user }  #require email unless logged in
  validates_format_of :author_email, :with => /\A([^@\s]+)@((?:[-a-z0-9A-Z]+\.)+[a-zA-Z]{2,})\z/, :unless => Proc.new{|record| record.user}
  validates_presence_of :author_ip, :unless => Proc.new{|record| record.user} #log ip unless logged in

  validates_presence_of :body, :topic

  after_create :monitor_topic
  after_create :notify_monitoring_users

  scope :with_query_options, lambda {
    select('sb_posts.*, topics.title as topic_title, forums.name as forum_name')
    .joins('inner join topics on sb_posts.topic_id = topics.id inner join forums on topics.forum_id = forums.id')
    .order('sb_posts.created_at desc')
  }
  scope :recent, -> { order('sb_posts.created_at ASC') }
  validate :check_spam

  def monitor_topic
    return unless user
    monitorship = Monitorship.where(:user_id => self.user.id, :topic_id => self.topic.id).first_or_initialize
    if monitorship.new_record?
      monitorship.update_attribute :active, true
    end
  end

  def notify_monitoring_users
    topic.notify_of_new_post(self)
  end

  def editable_by?(user)
    user && (user.id == user_id || user.admin? || user.moderator_of?(topic.forum_id))
  end

  def username
    user ? user.login : (author_name.blank? ? :anonymous.l : author_name)
  end

  def check_spam
    if configatron.has_key?(:akismet_key) && self.spam?
      self.errors.add(:base, :comment_spam_error.l)
    end
  end

  def dom_id
    ['sb_posts', id].join('-')
  end

end

app/controllers/sb_posts_controller.rb
class SbPostsController < BaseController
  before_action :find_post,      :except => [:index, :monitored, :search, :new, :create]
  before_action :login_required, :except => [:index, :search, :show, :monitored, :create]

  before_action :only => [:create] do |controller|
    login_required unless configatron.allow_anonymous_forum_posting
  end

  skip_before_action :verify_authenticity_token, :only => [:create] #remove for the create action
  before_action do |controller|
    #add it back unless anonymous posting is allowed
    verify_authenticity_token if controller.action_name.eql?('create') && !configatron.allow_anonymous_forum_posting
  end



  def index
    conditions = []
    [:user_id, :forum_id].each { |attr|
      conditions << SbPost.send(:sanitize_sql, ["sb_posts.#{attr} = ?", params[attr].to_i]) if params[attr]
    }
    conditions = conditions.any? ? conditions.collect { |c| "(#{c})" }.join(' AND ') : nil

    @posts = SbPost.with_query_options.where(conditions).page(params[:page])

    @users = User.distinct.where(:id => @posts.collect(&:user_id).uniq).to_a.index_by(&:id)
  end

  def search
    conditions = params[:q].blank? ? nil : SbPost.send(:sanitize_sql, ['LOWER(sb_posts.body) LIKE ?', "%#{params[:q]}%"])

    @posts = SbPost.with_query_options.where(conditions).page(params[:page])

    @users = User.distinct.where(:id => @posts.collect(&:user_id).uniq).to_a.index_by(&:id)
    render :action => :index
  end

  def monitored
    @user = User.find params[:user_id]
    @posts = SbPost.with_query_options.joins('INNER JOIN monitorships ON monitorships.topic_id = topics.id').where('monitorships.user_id = ? AND sb_posts.user_id != ?', params[:user_id], @user.id).page(params[:page])
  end

  def show
    respond_to do |format|
      format.html { redirect_to forum_topic_path(@post.forum_id, @post.topic_id) }
    end
  end

  def new
    if logged_in?
      redirect_to forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :anchor => 'reply-form', :page => params[:page] || '1') and return
    end
  end

  def create
    @topic = Topic.includes(:forum).where(:id => params[:topic_id].to_i, :forum_id => params[:forum_id].to_i).first
    if @topic.locked?
      respond_to do |format|
        format.html do
          flash[:notice] = :this_topic_is_locked.l
          redirect_to(forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id]))
        end
      end
      return
    end

    @forum = @topic.forum
    @post  = @topic.sb_posts.new(sb_post_params)

    @post.user = current_user if current_user
    @post.author_ip = request.remote_ip #save the ip address for everyone, just because

    if (logged_in? || verify_recaptcha(@post)) && @post.save
      respond_to do |format|
        format.html do
          redirect_to forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :anchor => @post.dom_id, :page => params[:page] || '1')
        end
        format.js
      end
    else
      flash.now[:notice] = @post.errors.full_messages.to_sentence
      respond_to do |format|
        format.html do
          redirect_to forum_topic_path({:forum_id => params[:forum_id], :id => params[:topic_id], :anchor => 'reply-form', :page => (params[:page] || '1')}.merge({:sb_post => params[:sb_post]}))
        end
        format.js
      end
    end
  end

  def edit
    authorize @post

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    authorize @post
    @post.update_attributes(sb_post_params)

    unless @post.valid?
      flash[:bad_reply] = :an_error_occurred.l
    end

    respond_to do |format|
      format.html do
        redirect_to forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :anchor => @post.dom_id, :page => params[:page] || '1')
      end
      format.js
      format.xml { head 200 }
    end
    
  end

  def destroy
    authorize @post

    @post.destroy
    flash[:notice] = :sb_post_was_deleted.l_with_args(:title => CGI::escapeHTML(@post.topic.title))
    # check for posts_count == 1 because its cached and counting the currently deleted post
    @post.topic.destroy and redirect_to forum_path(params[:forum_id]) if @post.topic.sb_posts_count == 1
    respond_to do |format|
      format.html do
        redirect_to forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :page => params[:page]) unless performed?
      end
      format.js
      format.xml { head 200 }
    end
  end

  protected
    def find_post
      @post = SbPost.find_by_id_and_topic_id_and_forum_id(params[:id].to_i, params[:topic_id].to_i, params[:forum_id].to_i) || raise(ActiveRecord::RecordNotFound)
    end

    def sb_post_params
      params[:sb_post].permit(:body, :author_email, :author_ip, :author_name, :author_url)
    end
end

app/views/sb_posts/_dummy_forum_post.html.haml
%tr
  %td
    =fa_icon "comment"
  %td
    = link_to h(post.title), user_post_path(post.user, post), :class => "entry-title", :rel => "bookmark", :target => '_blank'
  %td
    = post.comments.count
  %td
    = number_with_delimiter(post.view_count)
  %td
    \by
    %strong
      = h(post.user.display_name)

app/views/sb_posts/_edit.html.haml
= bootstrap_form_for post, :url => sb_post_path(:forum_id => post.forum_id, :topic_id => post.topic_id, :id => post), :layout => :horizontal, :html => {:class => "submit-via-ajax", :id => "edit-form-"+post.id.to_s} do |f|
  = f.text_area :body, :rows => 10, :id => "edit_post_body_" + post.id.to_s, :class => "rich_text_editor"
  = ajax_spinner_for "edit-form-" + post.id.to_s
  = submit_tag :save_changes.l, :class => 'btn btn-primary'
  or
  = link_to :cancel.l, '#', :class => 'btn btn-default editor-cancel', 'data-target' => "post-body-#{post.id}"

app/views/sb_posts/_edit_script.js.erb
console.log("configuring " + $('edit_post'));
$('edit_post').observe("ajax:before", function () {
    console.log("Submitting");
    $('editbox_spinner').show();
    $.save_rte
    console.log("saved");
    return false;
});
console.log("Setting button " + $('cancelButton'));
$('cancelButton').observe('click', function () {
    EditForm.cancel();
    return false;
});

app/views/sb_posts/_reply_form.html.haml
= bootstrap_form_for @post, :url => sb_posts_path(:forum_id => @forum, :topic_id => @topic, :page => @topic.last_page), :layout => :horizontal, :html => {:class => "submit-via-ajax", :id => "reply"} do |f|
  = f.text_area :body, :rows => 10, :style => "width: 99%;", :class => "rich_text_editor", :required => false

  - if !logged_in? && configatron.recaptcha_pub_key && configatron.recaptcha_priv_key
    = f.text_field :author_name
    = f.text_field :author_email, :required => true
    = f.text_field :author_url, :label => :comment_web_site_label.l

    = f.form_group do
      = recaptcha_tags :ajax => true

  = f.form_group do
    = ajax_spinner_for "reply"
    = f.primary :save_reply.l
    = :or.l
    = link_to :cancel.l, '#', :class => 'reply-toggle btn btn-default'

app/views/sb_posts/_reply_script.js.erb
$('new_post').observe("ajax:before", function () {
    console.log("Submitting");
    $('editbox_spinner').show();
    $.save_rte
    return false;
});
console.log("Setting button");
$('cancelButton').observe('click', function () {
    $('reply').hide();
    return false;
});

app/views/sb_posts/_sb_post.html.haml
%tr

  %td{:id=>"post-body-#{post.id}"}
    .editable
      - if logged_in?
        = link_to fa_icon("comment"), new_forum_topic_sb_post_path(post.topic.forum, post.topic), :class => 'reply-toggle'
      = post.body.html_safe
    .editor.hide

  %td.col-sm-3{:style => 'border-left:0'}
    %ul.list-unstyled
      -if post.user
        %li= link_to avatar_for(post.user), post.user
        %li= link_to truncate(h(post.username), :length => 15), user_path(post.user), :class => (post.topic.editable_by?(post.user) ? "admin" : nil)
        %li
          = :post.l.pluralize
          %span.badge.badge-info
            =post.user.sb_posts_count
      -else
        %li= image_tag(configatron.photo.missing_thumb, :class => 'thumbnail')
        %li= truncate(h(post.username), :length => 15)
      %li
        %a{"href"=>"##{post.dom_id}", "rel"=>"bookmark"}
          %abbr.updated{"title"=>"#{post.created_at.xmlschema}"}= time_ago_in_words(post.created_at)

      - if policy(post).update?
        %li
          = ajax_spinner_for "edit-post-#{post.id}"
          = link_to :edit_post.l, edit_forum_topic_sb_post_path(@forum, @topic, post), :class => 'edit-via-ajax', :id => "edit-post-#{post.id}"

      - if admin? && post.user && !post.user.admin?
        %li{"class"=>"make-moderator-#{post.user_id}"}
          = render :partial => '/moderators/toggle', :locals => {:user => post.user, :forum => @forum}

app/views/sb_posts/create.js.erb
<% if @post.new_record? %>
  reply = $('.reply');
  reply.prepend("<%=raw escape_javascript(render 'shared/messages') %>");
  message = reply.find('.alert')
  message.scrollTo();
<% else %>
  reply = $('.reply');
  posts_table = $('#posts');
  posts_table.append("<%= escape_javascript(render :partial => 'sb_posts/sb_post', :locals => {:post => @post}) %>")

  my_post = $('#post-body-<%= @post.id %>')
  my_post.scrollTo();

  $('#reply_spinner').addClass('hide');
  editable = my_post.find('.editable');

  editable.switchClass('','alert alert-info', 500,'easeOutCubic',function(){
	 editable.switchClass('alert alert-info','normal', 3000,'easeInCubic');
  });

  CKEDITOR.instances.sb_post_body.setData('')

  reply.addClass('hide');
<% end %>

<% if !logged_in? && configatron.has_key?(:recaptcha_pub_key) %>
	if($('dynamic_recaptcha')){
		Recaptcha.create('<%= configatron.recaptcha_pub_key %>', $('dynamic_recaptcha') )
	}
<% end %>

app/views/sb_posts/destroy.js.erb
post = $('#post-body-<%= @post.id %>');
post.remove();

app/views/sb_posts/edit.html.erb
<h1><%= :edit_post.l %></h1>

<h2><%= link_to h(@post.topic.title), forum_topic_path(@post.forum_id, @post.topic) %></h2>

<%= link_to(:delete_this_post.l, sb_post_path(@post, :forum_id => @post.forum_id, :topic_id => @post.topic, :page => params[:page]),
      :class => "utility", :method => :delete, data: { confirm: :are_you_sure_you_want_to_delete_this_post.l } ) %>

<%= error_messages_for :topic %>
<% form_for :post, :html => { :method => :patch },
     :url  => sb_post_path(@post, :forum_id => params[:forum_id], :id => params[:topic_id], :page => params[:page]) do |f| -%>
<%= f.text_area :body, :class => "rich_text_editor" %>
<%= submit_tag :save.l %> <%= :or.l %> <%= link_to :cancel.l, forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :page => params[:page]) %>
<% end -%>

app/views/sb_posts/edit.js.erb
post = $('#post-body-<%= @post.id %>');
editor = post.find('.editor');
editable = post.find('.editable');

editable.addClass('hide');
editor.html("<%= escape_javascript(render :partial => 'sb_posts/edit', :locals => {:post => @post}) %>");

$.remove_rte()
$.rte_posts();

post.scrollTo();

$('#edit-post-<%= @post.id %>_spinner').addClass('hide');

editor.toggleClass('hide');

app/views/sb_posts/index.html.haml
-@section = 'forums'
- @page_title = search_posts_title

-box do 

  .right=link_to :forums.l, forums_path
  %h3
    - if params[:q].blank?
      = @page_title
    - else
      ="#{:searching_for.l} '#{h params[:q]}'"

  %p.subtitle
    =link_to fa_icon("rss"), all_sb_posts_path(:format => 'rss')
    =:post_found.l(:count => @posts.size)

  %table.posts.wide{ :cellspacing => "0", :border => "0", :cellpadding => "0", :width => '100%'}
    - for post in @posts do
      - unless post == @posts.to_a.first
        %tr.spacer
          %td{ :colspan => "2" }
            \&nbsp;
      %tr.post{ :id => post.dom_id }
        %td.author.vcard
          .date
            %abbr.updated{ :title => post.created_at.xmlschema }
              = time_ago_in_words(post.created_at)

          -if post.user
            = avatar_for post.user    
            %span.fn
              = link_to truncate(h(post.username), :length => 15), user_path(post.user), :class => (post.topic.editable_by?(post.user) ? "admin" : nil)
            %span.posts= pluralize post.user.sb_posts_count, :post.l
          -else
            = image_tag(configatron.photo.missing_thumb, :height => '32', :width => '32', :class => 'photo')        
            %span.fn
              =truncate(h(post.username), :length => 15)

        %td.body.entry-content
          %p.topic
            = link_to(h(post.forum_name), forum_path(post.forum))
            \/
            = link_to h(post.topic_title), forum_topic_path(post.forum, post.topic)
          =raw post.body
        
  =paginate @posts, :theme => 'bootstrap'

app/views/sb_posts/monitored.html.erb
<% @page_title = "Posts that #{h @user.display_name} is monitoring" -%>

<h4><%= link_to @user.display_name, user_path(@user) %>'<%= 's '+:monitored_topics.l %></h4>
<ul class="flat">
<% @user.monitored_topics.limit(25).each do |topic| %>
  <li><%= link_to topic.title, forum_topic_path(topic.forum_id, topic) %></li>
<% end %>
</ul>

<h1><%= @page_title %></h1>
<p class="subtitle">
  <%= link_to fa_icon("rss"), monitored_all_sb_posts_path(:user_id => @user, :format => 'rss') %>
  <%= :post_found.l(:count => @posts.size) %>
</p>

<table border="0" cellspacing="0" cellpadding="0" class="posts wide">
<% for post in @posts do %>
<% unless post == @posts.to_a.first %>
<tr class="spacer">
  <td colspan="2">&nbsp;</td>
</tr>
<% end %>
<tr class="post hentry" id="<%= post.dom_id %>">
  <td class="author vcard">
    <div class="date">
      <abbr class="updated" title="<%= post.created_at.xmlschema %>">
      <% if post.created_at > Time.now.utc-24.hours%>
      <%= time_ago_in_words(post.created_at).sub(/about /, '') %> ago
      <% else %>
      <%= post.created_at.strftime("%b %e, %Y")%>
      <% end %>
      </abbr>
    </div>

    <%= avatar_for post.user %>
    <span class="fn"><%= link_to truncate(h(post.user.display_name), :length => 15), user_path(post.user), :class => (post.user == @posts.to_a.first.user ? "admin" : nil) %></span>
    <span class="posts"><%= pluralize post.user.sb_posts_count, 'post' %></span>
  </td>
  <td class="body entry-content">
    <p class="topic"><%= :topic.l %> <%= link_to h(post.topic_title), forum_topic_path(post.forum_id, post.topic_id) %></p>
    
    <%= post.body_html %>
  </td>
</tr>

<% end %>
</table>

<%= paginate @posts, :theme => 'bootstrap' %>

app/views/sb_posts/update.js.erb
post = $('#post-body-<%= @post.id %>');
editor = post.find('.editor');
editable = post.find('.editable');

editor.addClass('hide');
editable.html("<%=raw escape_javascript(@post.body) %>");
post.scrollTo();

editable.switchClass('hide','alert alert-info', 500,'easeOutCubic',function(){
	editable.switchClass('alert alert-info','normal', 3000,'easeInCubic');
});