config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection
  end

  get '/base/:action' => 'base'

  get '/forums/recent' => 'sb_posts#index', :as => :recent_forum_posts
  get '/photos/recent' => 'photos#recent', :as => :recent_photos

  resources :authorizations
  get '/auth/:provider/callback' => 'authorizations#create', :as => :callback
  get '/auth/failure' => 'authorizations#failure'

  resources :sb_posts, :as => 'all_sb_posts' do
    collection do
      get :search
      get :monitored
    end
  end

  resources :monitorship
  resources :sb_posts do
    collection do
      get :search
      get :monitored
    end
  end

  resources :forums do
    resources :sb_posts

    resources :moderators
    resources :topics do
      resources :sb_posts
      resource :monitorship
    end
  end

  get '/forums' => 'forums#index', :as => :forum_home

  get 'sitemap.xml' => 'sitemap#index', :format => 'xml'
  get 'sitemap' => 'sitemap#index'

  get '/' => 'base#site_index', :as => :home

  root to: "base#site_index"



  # scope "/admin" do
  #   get 'dashboard' => 'homepage_features#index', :as => :admin_dashboard
  #   get 'clear_cache' => 'admin#clear_cache', :as => :admin_clear_cache
  # end

  get 'pages/:id' => 'pages#show', :as => :pages


  get '/login' => 'sessions#new', :as => :login
  get '/signup' => 'users#new', :as => :signup
  get '/logout' => 'sessions#destroy', :as => :logout

  get '/signup/:inviter_id/:inviter_code' => 'users#new', :as => :signup_by_id
  get '/forgot_password' => 'password_resets#new', :as => :forgot_password
  resources :password_resets

  match '/forgot_username' => 'users#forgot_username', :as => :forgot_username, :via => [:get, :post]

  post '/resend_activation/:id' => 'users#resend_activation', :as => :resend_activation

  get '/new_clipping' => 'clippings#new_clipping'
  post '/load_images_from_uri' => 'clippings#load_images_from_uri', :format => 'js'
  get '/clippings(/page/:page)' => 'clippings#site_index', :as => :site_clippings
  get '/clippings.rss' => 'clippings#site_index', :as => :rss_site_clippings, :format => 'rss'

  get '/featured(/page/:page)' => 'posts#featured', :as => :featured
  get '/featured.rss' => 'posts#featured', :as => :featured_rss, :format => 'rss'
  get '/popular(/page/:page)' => 'posts#popular', :as => :popular
  get '/popular.rss' => 'posts#popular', :as => :popular_rss, :format => 'rss'
  get '/recent(/page/:page)' => 'posts#recent', :as => :recent
  get '/recent.rss' => 'posts#recent', :as => :recent_rss, :format => 'rss'
  get '/rss' => 'base#rss_site_index', :as => :rss_redirect
  get '/site_index.rss' => 'base#site_index', :as => :rss, :format => 'rss'
  get '/advertise' => 'base#advertise', :as => :advertise
  get '/footer_content' => 'base#footer_content', :as => :footer_content

  get '/account/edit' => 'users#edit_account', :as => :edit_account_from_email

  get '/friendships.xml' => 'friendships#index', :as => :friendships_xml, :format => 'xml'
  get '/friendships' => 'friendships#index', :as => :friendships

  get 'manage_photos' => 'photos#manage_photos', :as => :manage_photos
  post 'manage_photos' => 'photos#create_photos', :as => :create_photos

  post 'create_photo.js' => 'photos#create', :as => :create_photo, :format => 'js'

  resources :sessions
  resources :statistics do
    collection do
      get :activities
      get :activities_chart
    end
  end

  resources :tags do
    get :auto_complete_for_tag_name, :on => :collection
  end
  get '/tags/:id/:type' => 'tags#show', :as => :show_tag_type
  get '/search/tags' => 'tags#show', :as => :search_tags

  resources :categories
  post '/categories/show_tips' => 'categories#show_tips', :as => :categories_show_tips

  resources :events, :concerns => :paginatable do
    collection do
      get :past
      get :ical
    end
    member do
      get :clone
    end
    resources :rsvps
  end
  scope "/:commentable_type/:commentable_id" do
    resources :comments, :as => :commentable_comments do
      member do
        get :unsubscribe
        put :approve
      end
    end
  end
  resources :comments do
    collection do
      delete :delete_selected
    end
  end
  resources :comments

  resources :homepage_features
  resources :metro_areas
  resources :ads

  resources :activities

  resources :users, :concerns => :paginatable do

    collection do
      post 'return_admin'
      delete 'delete_selected'
    end
    member do
      get 'dashboard'
      get 'edit_account'
      get 'invite'
      get 'signup_completed'
      get 'activate'

      patch 'toggle_moderator'
      patch 'toggle_featured'

      patch 'change_profile_photo'
      patch 'update_account'
      patch 'deactivate'

      get 'welcome_photo'
      get 'welcome_about'
      get 'welcome_invite'
      get 'welcome_complete'

      post 'assume'

      get 'statistics'
      match 'crop_profile_photo', :via => [:get, :put, :patch]
      match 'upload_profile_photo', :via => [:get, :put, :patch]
    end

    resources :friendships do
      collection do
        get :accepted
        get :pending
        get :denied
      end
      member do
        patch :accept
        patch :deny
      end
    end

    resources :photos, :concerns => :paginatable

    resources :posts, :concerns => :paginatable do
      collection do
        # get 'manage(/page/:page)', :action => :manage
        match :manage, :via => [:get, :post]
      end

      member do
        post :send_to_friend
        patch :update_views
        get :category_tips_update
        get :preview
      end
    end

    resources :clippings

    resources :activities, :concerns => :paginatable do
      collection do
        get :network
      end
    end

    resources :invitations

    resources :favorites
    resources :messages do
      get :auto_complete_for_username, :on => :collection
      collection do
        post :delete_message_threads
        post :delete_selected
      end
    end

    resources :comments
    resources :photo_manager

    resources :albums do
      resources :photos do
        collection do
          post :swfupload
          get :slideshow
        end
      end
    end

  end

  scope '/:favoritable_type/:favoritable_id' do
    resources :favorites
  end

  resources :votes
  resources :invitations
  get '/users/:user_id/posts/category/:category_name' => 'posts#index', :as => :users_posts_in_category
  post '/users/metro_area_update' => 'users#metro_area_update', :as => :users_metro_area_update


end

app/controllers/activities_controller.rb
class ActivitiesController < BaseController
  before_action :login_required,  :except => :index
  before_action :find_user,       :only => :network

  before_action :require_current_user,            :except => [:index, :destroy]
  before_action :require_ownership_or_moderator,  :only   => :destroy


  def network
    @activities = @user.network_activity(:per_page => 15, :page => params[:page])
  end

  def index
    @activities = User.recent_activity(:per_page => 30, :page => params[:page], :limit => 1000)
    @popular_tags = popular_tags(30).to_a
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html {redirect_to :back and return}
      format.js
    end
  end

  private
    def require_ownership_or_moderator
      @activity = Activity.find(params[:id])

      unless @activity && @activity.can_be_deleted_by?(current_user)
        redirect_to :controller => 'sessions', :action => 'new' and return false
      end
      return @user
    end

end

app/views/activities/_activity.html.haml
%tr{:id => 'activity-' + activity.id.to_s }
  %td
    =time_ago_in_words(activity.created_at)
  %td 
    =link_to activity.user.login.capitalize, user_path(activity.user.friendly_id)  
    - if activity.item
      - case activity.item_type
        - when 'Post'
          =:wrote_a_post.l
          = link_to activity.item.title, user_post_path(activity.item.user, activity.item)
        - when 'Photo'
          =:uploaded_a_photo.l
          = link_to image_tag(activity.item.photo.url(:thumb), :class => 'thumbnail col-sm-1 pull-right'), user_photo_path(activity.item.user, activity.item)
        - when 'Album'
          =:created_an_album.l
          = link_to activity.item.title, user_album_path(activity.item.user, activity.item)
        - when 'Topic'
          =:started_a_topic.l
          -topic = activity.item
          = link_to truncate_words(topic.title), forum_topic_path(topic.forum, topic)
        - when 'SbPost'
          =:added_to_a_forum_topic.l
          - topic = activity.item.topic
          = link_to truncate_words(activity.item.body), forum_topic_path(topic.forum, topic)
        - when 'Comment'
          =:left_a_comment.l
          = link_to truncate_words(activity.item.comment), commentable_url(activity.item)
        - when 'Favorite'
          =:favorited.l
          = link_to " a #{activity.item.favoritable.class.to_s.humanize.downcase}", user_favorite_path(activity.item.user, activity.item)
        - when 'Clipping'
          =:added_a_clipping.l
          = link_to image_tag( activity.item.image_uri(:thumb), :class => 'thumbnail col-sm-1 pull-right'), user_clipping_path(activity.item.user, activity.item)
        - when 'Invitation'
          =:invited_friends.l
        - when 'Event'
          =:posted_an_event.l
          = link_to activity.item.name, event_path(activity.item)
        - when 'Rsvp'
          =:rsvped_for_an_event.l
          = link_to activity.item.event.name, event_path(activity.item.event)
        -else
          =render :partial => 'activities/unhandled_item', :locals => {:activity => activity}
    - else
      - case activity.action
        - when 'updated_profile'
          =:updated_their_profile.l
        - when 'logged_in'
          =:logged_into_the_site.l
        - when 'joined_the_site'
          =:joined_the_site.l(:site => configatron.community_name)
        - else
          = " #{activity.action.humanize.downcase }"
  %td
    -if activity.can_be_deleted_by?(current_user)
      =link_to fa_icon("times"), activity, :remote => true, :method => 'delete', 'data-manual-confirm' => :are_you_sure.l, :class => 'clear-right pull-right btn btn-danger btn-xs delete-via-ajax'

app/views/activities/_icon.haml
- if activity.item
  - case activity.item_type
    - when 'Post', 'SbPost', 'Topic'
      = image_tag 'icons/post.png', :plugin => 'community_engine'
    - when 'Favorite'
      = image_tag 'icons/heart.png', :plugin => 'community_engine'
    - when 'Photo'
      = image_tag 'icons/picture.png', :plugin => 'community_engine'
    - when 'Comment'
      = image_tag 'icons/comment.png', :plugin => 'community_engine'
    - when 'Clipping'
      = image_tag 'icons/clipping.png', :plugin => 'community_engine'
- else
  =image_tag 'icons/activity_default.png', :plugin => 'community_engine'

app/views/activities/_unhandled_item.html.haml
/ Override this partial to handle display of activities items which are not handled by default by CE.

app/views/activities/destroy.js.erb
$('#activity-<%= @activity.id.to_s %>').switchClass('', 'hide', 'slow', 'easeOutCubic');

app/views/activities/index.html.haml
-@section = 'activities'
-@page_title = 'Recent Activities'
.fresh
  %h3= :whats_fresh.l
  %table{:width => '100%'}
    =render :partial => "activities/activity", :collection => @activities
  =paginate @activities, :theme => 'bootstrap'

-widget do
  %h4
    .small= :tags.l
  %p
    - tag_cloud @popular_tags, %w(nube1 nube2 nube3 nube4 nube5) do |tag, css_class|
      = link_to tag.name, tag_path(tag.to_param), :class => css_class
  %p=link_to fa_icon('plus-circle', :text => :all_tags.l.downcase.capitalize), tags_path

app/views/activities/network.html.haml
=render :partial => 'users/dashboard_nav'
  
-unless @activities.empty?
  %h3=:activity_from_your_network.l
  %table{:width => '100%'}
    =render :partial => "activities/activity", :collection => @activities
  -if @activities.total_count > 1
    = paginate @activities, :theme => 'bootstrap'
-else
  =:you_have_no_network_activity_yet.l 
  = link_to :add_some_friends_to_get_started.l, users_path